VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsWeer"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public datum As String
Public dagweek As String
Public kanszon As Integer
Public kansregen As Integer
Public minmmregen As Integer
Public maxmmregen As Integer
Public mintemp As Integer
Public mintempmax As Integer
Public maxtemp As Integer
Public maxtempmax As Integer
Public windrichting As String
Public windkracht As Integer

